FROM maven:3.8.5-openjdk-17 as builder
COPY . .
RUN mvn package -pl spi -am -DskipTests

FROM quay.io/keycloak/keycloak:23.0.2

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV PROXY_ADDRESS_FORWARDING=true
ENV KC_PROXY=edge
ENV KC_HOSTNAME_STRICT=false
ENV KC_HTTP_ENABLED=true
ENV KC_HOSTNAME_STRICT_BACKCHANNEL=true
COPY ./themes /opt/keycloak/themes
COPY --from=builder ./spi/target/custom-spi.jar /opt/keycloak/providers/custom-spi.jar

ENV KC_DB=postgres
ENV KC_DB_SCHEMA=public

WORKDIR /opt/keycloak
EXPOSE 8080
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
