server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/political-governance
          jwk-set-uri: http://localhost:8082/realms/political-governance/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5433/pgf
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # You can change this to create if you want to initialize the schema
    show-sql: true # Set this to true to see SQL queries in the console
infura-endpoint:
private-key:

logging:
  level:
    org:
      springframework:
        security: DEBUG

